float:
  euclidean:
  - base_args: ['@metric']
    constructor: MariaDB
    disabled: false
    docker_tag: ann-benchmarks-mariadb
    module: ann_benchmarks.algorithms.mariadb
    name: mariadb
    run_groups:
      normal:
        arg_groups: [{txt: 'orig', M: [3, 4, 5, 6, 8, 16, 32, 48], engine: 'MyISAM'}]
        args: {}
        query_args: [[10, 20, 30, 40]]
      large-ef: # slow, use --run 1, the search is deterministic anyway
        arg_groups: [{txt: 'orig', M: [3,4,5,6,8,12], engine: 'MyISAM'}]
        args: {}
        query_args: [[800,1200]]
